"""Add LocationHistory table for user mobility tracking

Revision ID: location_history_001
Revises: ecec8369c35d
Create Date: 2024-12-19 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'location_history_001'
down_revision = 'ecec8369c35d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('location_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('detection_method', sa.String(length=20), nullable=True),
    sa.Column('accuracy', sa.Float(), nullable=True),
    sa.Column('is_location_change', sa.Boolean(), nullable=True),
    sa.Column('distance_from_previous', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('location_history')
    # ### end Alembic commands ###